### ISSUE TITLE
Just what I needed, OTA Arduino style!

### ISSUE THREAD

**Issue by derekmulcahy** [Johboh/ConnectionHelper#1]
Hi,

Just wanted to say, bravo!

I was looking for something similar to the Arduino IDE method of OTA updates for the Esp32 and IDF projects and this works perfectly. More features than I need at the moment but all implemented clearly and succinctly.

Thanks,
Derek

**Comment by Johboh** [comment]
Thanks @derekmulcahy!
Let me know if there are any issues or missing functionality and I will look into it.
